@startuml
'https://plantuml.com/class-diagram

class Rectangle extends Shape
{
    - length: double
    - width: double
    + perimeter(): double
    + area(): double
    + to_string(): string
}

@enduml